version: '3.5'

services:
  app:
    build:
      context: .
      args:
        - E2E=true
        - NPM_COMMAND=start:test
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 8000:8000
    container_name: riksutin_test

  db:
    image: postgres:15.7
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    container_name: riksutin_test_db

  redis:
    image: redis:7-alpine
    container_name: riksutin_test_redis
